
#ifndef BUINSKII_FOCUSER_FIRMWARE_FOCUSHANDCONTROLLER_H
#define BUINSKII_FOCUSER_FIRMWARE_FOCUSHANDCONTROLLER_H


class FocusHandController {

};


#endif //BUINSKII_FOCUSER_FIRMWARE_FOCUSHANDCONTROLLER_H
